apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment-hello
  namespace: hello
spec:
  selector:
    matchLabels:
      app: metrics
      department: sales
  replicas: 3
  template:
    metadata:
      labels:
        app: metrics
        department: sales
    spec:
      containers:
      - name: hello
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:2.0"

apiVersion: v1
kind: Service
metadata:
  name: my-service-hello
  namespace: hello
spec:
  selector:
    app: metrics
    department: sales
  type: LoadBalancer
  loadBalancerIP: 10.100.241.183
  ports:
  - port: 80
    targetPort: 8080
